packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  dotenv: '^16.4.0'
  typescript: '^5.8.0'
  '@typescript/native-preview': 'latest'
  '@types/node': '^25.0.3'
  zod: '^3.24.0'
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  hono: '^4.7.0'
  '@hono/node-server': '^1.14.0'
  react: '^19.2.3'
  react-dom: '^19.2.3'
  '@types/react': '^19.2.7'
  '@types/react-dom': '^19.2.3'
  '@testing-library/jest-dom': '^6.9.1'
  '@testing-library/react': '^16.3.1'
  tailwindcss: '^4.0.0'
  vite: npm:@voidzero-dev/vite-plus-core@latest
  '@tanstack/react-start': '^1.144.0'
  vite-plus: latest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
